version: "3.8"

services:

  backend:
    build:
      context: backend/
    restart: unless-stopped
    env_file:
      - .env
      - backend/.env
    depends_on:
      database:
        condition: service_healthy

  database:
    build:
      context: database/
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
      - database/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  frontend:
    build: 
      context: frontend/
    env_file:
      - .env
      - frontend/.env
    ports:
      - 80:80
      - 443:443
    # command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - backend
    
volumes:
  db-data:
