version: "3.8"

services:

  backend:
    build:
      context: backend/
    container_name: transcendance_backend
    restart: unless-stopped
    env_file:
      - .env
      - backend/.env
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  database:
    build:
      context: database/
    container_name: transcendance_database
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
      - database/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: 
      context: frontend/
    container_name: transcendance_frontend
    env_file:
      - .env
      - frontend/.env
    ports:
      - 443:443
    # command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - backend
    
volumes:
  db-data:
