version: "3.8"

services:

  backend:
    build:
      context: backend/
    container_name: transcendance_backend
    restart: unless-stopped
    env_file:
      - .env
      - backend/.env
    ports:
      - 8000:8000

  database:
    build:
      context: database/
    container_name: transcendance_database
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
      - database/.env
    ports:
      - 5432:5432

  frontend:
    build: 
      context: frontend/
    container_name: transcendance_frontend
    env_file:
      - .env
      - frontend/.env
    ports:
      - 443:443
      - 80:80
    
volumes:
  db-data:
