"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

from corsheaders.defaults import default_headers

env = environ.Env(
    TRANS_DB_NAME=(str, 'transcendence'),
    TRANS_DB_USER=(str, 'postgres'),
    TRANS_DB_PASS=(str, 'password'),
    TRANS_DB_HOST=(str, '127.0.0.1'),
    TRANS_DB_PORT=(str, '5432'),
    MYPY_DJANGO_CONFIG=(str, './mypy.ini'),
    CORS_ALLOWED_ORIGINS=(list, ["http://localhost:8080", "http://localhost"]),
    JWT_SECRET=(str, 'SECRET'),
    PASSWORD_42AUTH=(str, ''),
    APP_NAME=(str, 'EpicPong'),
    CLIENT_ID=(str, "NO CLIENT ID"),
    CLIENT_SECRET=(str, "NO CLIENT SECRET"),
    REDIRECT_URI=(str, "http://localhost:8080/auth/42-register"),
    AUTHORIZE_URL=(str, "https://api.intra.42.fr/oauth/authorize"),
    TOKEN_URL=(str, "https://api.intra.42.fr/oauth/token"),
    DOMAIN_NAME=(str, "localhost"),
    SECRET_KEY=(str, 'django-insecure-otc*6$yc^vbe&m1uzzt!0jt^l=4r4=q&3#voh5een44bu4v)u#')
)

DOMAIN_NAME = env("DOMAIN_NAME")

CORS_ALLOWED_ORIGINS = [*env('CORS_ALLOWED_ORIGINS'), f"http://{DOMAIN_NAME}:8080", f"http://{DOMAIN_NAME}:8000", f"https://{DOMAIN_NAME}"]
CORS_ALLOW_HEADERS = [*default_headers, 'X-CSRFToken']
CORS_ALLOW_CREDENTIALS = True

UNAUTHENTICATED_REQUESTS = ['/authentication/login', '/authentication/register', '/authentication/logout', '/server_info/', '/authentication/42-register/', '/authentication/login42']
UNAUTHENTICATED_2FA_REQUESTS = ['/authentication/check-code','/authentication/logout']

CSRF_TRUSTED_ORIGINS = ["http://localhost:8080", "http://localhost:8000", f"https://{DOMAIN_NAME}", f"http://{DOMAIN_NAME}:8080", f"http://{DOMAIN_NAME}:8000"]
CSRF_COOKIE_DOMAIN = f"{DOMAIN_NAME}"
# CSRF_COOKIE_DOMAIN = f"42lausanne.ch"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "0.0.0.0", "localhost", f"{DOMAIN_NAME}", "backend"]

SESSION_SAVE_EVERY_REQUEST = True

# Application definition
INSTALLED_APPS = [
    'daphne',
    'game',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions',
    'rest_framework',
    'corsheaders',

    'core',
    'friends',
    'blocks',
    'backend',
    'chats',
    'authentication',
    'tournament_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.middleware.CustomAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('TRANS_DB_NAME'),
        'USER': env('TRANS_DB_USER'),
        'PASSWORD': env('TRANS_DB_PASS'),
        'HOST': env('TRANS_DB_HOST'),
        'PORT': env('TRANS_DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 3600

AUTH_USER_MODEL = 'core.EpicPongUser'

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
