# Generated by Django 4.2.10 on 2024-03-02 18:03

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=game.models.current_time),
        ),
    ]
