# Generated by Django 5.0 on 2024-03-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_created_at'),
        ('tournament_app', '0004_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(blank=True, choices=[('no', 'Not Started'), ('pool', 'Pool Phase'), ('eight', 'Eight Phase'), ('quarter', 'Quarter Phase'), ('semi', 'Semi Phase'), ('final', 'Final Phase')], null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament_app.tournament'),
        ),
    ]
