# Generated by Django 5.0 on 2024-03-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_phase_game_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(blank=True, choices=[('no', 'Not Started'), ('pool', 'Pool Phase'), ('eight', 'Eight Phase'), ('quarter', 'Quarter Phase'), ('semi', 'Semi Phase'), ('final', 'Final Phase'), ('end', 'End')], null=True),
        ),
    ]
