# Generated by Django 4.2.10 on 2024-02-14 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'managed': True, 'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('user', 'friend')},
        ),
        migrations.AlterModelTable(
            name='friends',
            table='friends',
        ),
    ]
