# Generated by Django 5.0 on 2024-02-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_open', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('phase', models.CharField(choices=[('no', 'Not Started'), ('pool', 'Pool Phase'), ('eight', 'Eight Phase'), ('quarter', 'Quarter Phase'), ('semi', 'Semi Phase'), ('final', 'Final Phase')], default='no')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('no', 'Not Started'), ('pool', 'Pool Phase'), ('eight', 'Eight Phase'), ('quarter', 'Quarter Phase'), ('semi', 'Semi Phase'), ('final', 'Final Phase')])),
                ('score_player1', models.PositiveIntegerField(default=0)),
                ('score_player2', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='not_started', max_length=20)),
                ('ready_player1', models.BooleanField(default=False)),
                ('ready_player2', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('goal_average', models.IntegerField(default=0)),
                ('goal_conceded', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament_app.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'alias')},
            },
        ),
    ]
