# Generated by Django 4.2.10 on 2024-02-09 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('points', models.PositiveIntegerField(default=0)),
                ('goal_average', models.IntegerField(default=0)),
                ('goal_conceded', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_open', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('phase', models.CharField(choices=[('no', 'not begin'), ('pool', 'Pool Phase'), ('eighth', 'Eighth Phase'), ('quarter', 'Quarter Phase'), ('semi', 'Semi Phase'), ('final', 'Final Phase')], default='no', max_length=20)),
                ('creator_alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournament', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(through='tournament_app.RegistrationTournament', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_app.registrationtournament')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_app.tournament')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='ranking',
            field=models.ManyToManyField(related_name='tournament_ranking', through='tournament_app.TournamentRanking', to='tournament_app.registrationtournament'),
        ),
        migrations.AddField(
            model_name='registrationtournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_app.tournament'),
        ),
        migrations.AddField(
            model_name='registrationtournament',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=50)),
                ('score_player1', models.PositiveIntegerField(default=0)),
                ('score_player2', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='not_started', max_length=20)),
                ('ready_player1', models.BooleanField(default=False)),
                ('ready_player2', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_app.tournament')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registrationtournament',
            unique_together={('tournament', 'alias')},
        ),
    ]
