# Generated by Django 5.0 on 2024-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtournament',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
