# Generated by Django 5.0 on 2024-03-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0004_delete_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='phase',
            field=models.CharField(choices=[('no', 'Not Started'), ('pool', 'Pool Phase'), ('eight', 'Eight Phase'), ('quarter', 'Quarter Phase'), ('semi', 'Semi Phase'), ('final', 'Final Phase'), ('end', 'End')], default='no'),
        ),
    ]
