# Generated by Django 4.2.10 on 2024-02-15 14:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicponguser',
            name='socket_id',
            field=models.CharField(default=core.models.random_token, max_length=128),
        ),
    ]
