# Generated by Django 5.0 on 2024-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicponguser',
            name='avatar',
            field=models.CharField(default='', max_length=512),
        ),
    ]
