# Generated by Django 5.0 on 2024-03-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_epicponguser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicponguser',
            name='id42',
            field=models.IntegerField(default=0),
        ),
    ]
