# Generated by Django 4.2.10 on 2024-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_epicponguser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicponguser',
            name='status',
            field=models.CharField(default='online', max_length=128),
        ),
    ]
