# Generated by Django 5.0 on 2024-02-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_epicponguser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicponguser',
            name='a2f_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epicponguser',
            name='a2f_token',
            field=models.CharField(default='', max_length=128),
        ),
    ]
