# Generated by Django 4.2.10 on 2024-02-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_epicponguser_socket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicponguser',
            name='avatar',
            field=models.CharField(default='default-avatar', max_length=128),
        ),
    ]
