# Generated by Django 5.0 on 2024-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_epicponguser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicponguser',
            name='avatar',
            field=models.TextField(default=''),
        ),
    ]
