# Generated by Django 5.0 on 2024-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_epicponguser_id42'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicponguser',
            name='id42',
            field=models.CharField(default=''),
        ),
    ]
