# Generated by Django 5.0 on 2024-03-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_epicponguser_a2f_enabled_epicponguser_a2f_token'),
        ('core', '0003_epicponguser_status'),
        ('core', '0004_alter_epicponguser_id42'),
    ]

    operations = [
    ]
